# Generated by Django 5.2.7 on 2025-10-16 08:10

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True)),
                ('status', models.CharField(choices=[('BACKLOG', 'Backlog'), ('IN_PROGRESS', 'In Progress'), ('DONE', 'Done')], default='BACKLOG', max_length=20)),
            ],
        ),
    ]
